Remove challengutils dependency
Sage-Bionetworks/synapseformation pull request #11
Opened 2020-03-19 02:08 UTC by thomasyu888

#3

2020-03-31 17:59 UTC, kdaily requested changes
LG overall, few changes! THanks

2020-03-31 17:59 UTC, kdaily commented on synapseformation/create.py
> +            Challenge object
dictionary in format of Synapse challenge object response

2020-03-31 17:59 UTC, kdaily commented on synapseformation/create.py
> +    def _get_challenge(self, projectId) -> 'Challenge':
returns dict

2020-03-31 17:59 UTC, kdaily commented on synapseformation/create.py
> +                          participantTeamId: str) -> 'Challenge':
return dict

2020-03-31 17:59 UTC, kdaily commented on synapseformation/create.py
> +            Challenge object
dict

2020-03-31 17:59 UTC, kdaily commented on synapseformation/create.py
> +    def get_or_create_challenge(self, projectId, *args, **kwargs) -> 'Challenge':
dict

2020-03-31 17:59 UTC, kdaily commented on synapseformation/create.py
> +    def get_or_create_challenge(self, projectId, *args, **kwargs) -> 'Challenge':
only kwargs

2020-04-17 23:38 UTC, thomasyu888 commented on requirements.txt
> +synapseclient==1.9.4
```suggestion
synapseclient==2.0.0
```

2020-04-29 21:13 UTC, kdaily approved these changes

2020-04-30 03:26 UTC, merged