Create or find Synapse object instead of update
Sage-Bionetworks/synapseformation pull request #12
Opened 2020-03-19 06:02 UTC by thomasyu888

#9 
#8 
#7 
#10

2020-03-31 17:50 UTC, kdaily requested changes
only use `**kwargs`, not `*args`

2020-03-31 17:50 UTC, kdaily commented on synapseformation/create.py
> +            only_create: Only create entities.  Default is True, which
extra space after period

2020-03-31 17:50 UTC, kdaily commented on synapseformation/create.py
> +        except SynapseHTTPError:
check the error response or code

2020-03-31 17:50 UTC, kdaily commented on synapseformation/create.py
> +                raise ValueError("only_create is set to True.")
print contents of the original exception also

2020-03-31 17:50 UTC, kdaily commented on synapseformation/create.py
> +            assert entity.properties.concreteType == entity_tmp.properties.concreteType, "Different types."  # pylint: disable=line-too-long
shouldn't be an assertion, should be a test and raise an error (ValueError)

2020-03-31 17:50 UTC, kdaily commented on synapseformation/create.py
> +            assert entity.properties.concreteType == entity_tmp.properties.concreteType, "Different types."  # pylint: disable=line-too-long
TypeError?

2020-03-31 17:50 UTC, kdaily commented on synapseformation/create.py
> +                raise ValueError("only_create is set to True.")
get error message from HTTP error too

2020-04-06 05:18 UTC, thomasyu888 commented on synapseformation/create.py
> +from functools import partial
```suggestion
```

2020-04-17 20:34 UTC, thomasyu888 commented on synapseformation/create.py
> +    def _find_by_obj_or_create(self, obj: 'Object') -> 'Object':
Use Union

2020-04-29 21:07 UTC, kdaily approved these changes

2020-04-29 21:07 UTC, kdaily commented on tests/test_create.py
> +    mocked_409 = SynapseHTTPError("foo", response=Mock(status_code=409))
note what a 409 error is (a conflict) - is this documented in our REST API?

2020-04-30 03:27 UTC, merged